ALTER TABLE ingestion_runs ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ;
ALTER TABLE ingestion_runs ADD COLUMN IF NOT EXISTS error_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ingestion_runs ADD COLUMN IF NOT EXISTS rate_limited_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ingestion_runs ADD COLUMN IF NOT EXISTS rate_limit_events JSONB;
ALTER TABLE ingestion_runs ADD COLUMN IF NOT EXISTS next_scheduled_at TIMESTAMPTZ;
